### ISSUE TITLE
entité competence

### ISSUE THREAD

**Issue by jonathan-klh** [jonathan-klh/develops#5]
entité langage pour lié les différentes compétences a un utilisateur,
et aussi lors d'une recherche pouvoir chercher par langage de prog

**Comment by apn-dev** [comment]
Plutot faire une entité compétence. Avec un descriptif et le niveau dans cette compétence. C'est plus général. Puis dans un second temps faire une tables avec toutes les compétences possibles et pouvoir compléter son profil avec ces competence. Faire pareil avec les niveaux.
